### ISSUE TITLE
Add some way to fetch js.html.*Element based on tag name

### ISSUE THREAD

**Issue by benmerckx** [haxetink/tink_domspec#1]
I'm looking for a way to go from `'div'` to `js.html.DivElement` etc. It should be useful to type `EventFrom` properly. The letter casing is not consistent so I think mapping it like `tink.domspec.Tags` is probably the best way. I can contribute if it's something that fits here?

**Comment by benmerckx** [comment]
Just read the readme again, you probably don't want this in here :) Leaving it open in case you can point me to someplace else.

**Comment by benmerckx** [comment]
Hmm, stripping Element off and lowercasing it in a macro should just work :)

**Comment by back2dos** [comment]
Not really. You have `AnchorElement <-> a` and other things. But `Tags` does have all the info in principle (although, it's not 100% complete). If it's `GlobalAttributes`, then it's `Element` and if its `<Name>Attribute` then it's `<Name>Element`.

**Comment by back2dos** [comment]
Oh, and better yet `button -> InputElement` :D

So yeah, this is probably the closest thing there is to a comprehensive mapping. Perhaps some more exotic tags are missing too and I did intentionally skip some deprecated ones, but if there's anything you feel like adding, please feel free ;)

**Comment by benmerckx** [comment]
You're right of course. I didn't have all the pieces connected in my head yet. This was all I needed. (It's missing a `return` though): https://github.com/haxetink/tink_domspec/blob/master/src/tink/domspec/Macro.hx#L13
