### ISSUE TITLE
Allow custom Element type name

### ISSUE THREAD

**Issue by kevinresol** [haxetink/tink_domspec#7]
Now it parses from the Attr name (e.g. `InputAttr` -> `InputElement`) which is not very flexible.

For example I just added `ins/del` element, they have their own attributes in additional to the global ones. But they don't have a separate type `InsElement/DelElement`. So we should type them as plain `Element`

**Comment by back2dos** [comment]
Well, in this particular case, [`ModElement`](https://api.haxe.org/js/html/ModElement.html) is what you want, but yeah, we should probably add some meta to allow customizing this.
